package com.lab.kot.school.model.eo;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Oct 02 20:42:59 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SSectionEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        SectionId,
        SectionCode,
        SectionName,
        ActiveYn;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int SECTIONID = AttributesEnum.SectionId.index();
    public static final int SECTIONCODE = AttributesEnum.SectionCode.index();
    public static final int SECTIONNAME = AttributesEnum.SectionName.index();
    public static final int ACTIVEYN = AttributesEnum.ActiveYn.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SSectionEOImpl() {
    }

    /**
     * Gets the attribute value for SectionId, using the alias name SectionId.
     * @return the value of SectionId
     */
    public Long getSectionId() {
        return (Long) getAttributeInternal(SECTIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SectionId.
     * @param value value to set the SectionId
     */
    public void setSectionId(Long value) {
        setAttributeInternal(SECTIONID, value);
    }

    /**
     * Gets the attribute value for SectionCode, using the alias name SectionCode.
     * @return the value of SectionCode
     */
    public String getSectionCode() {
        return (String) getAttributeInternal(SECTIONCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SectionCode.
     * @param value value to set the SectionCode
     */
    public void setSectionCode(String value) {
        setAttributeInternal(SECTIONCODE, value);
    }

    /**
     * Gets the attribute value for SectionName, using the alias name SectionName.
     * @return the value of SectionName
     */
    public String getSectionName() {
        return (String) getAttributeInternal(SECTIONNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for SectionName.
     * @param value value to set the SectionName
     */
    public void setSectionName(String value) {
        setAttributeInternal(SECTIONNAME, value);
    }

    /**
     * Gets the attribute value for ActiveYn, using the alias name ActiveYn.
     * @return the value of ActiveYn
     */
    public String getActiveYn() {
        return (String) getAttributeInternal(ACTIVEYN);
    }

    /**
     * Sets <code>value</code> as the attribute value for ActiveYn.
     * @param value value to set the ActiveYn
     */
    public void setActiveYn(String value) {
        setAttributeInternal(ACTIVEYN, value);
    }

    /**
     * @param sectionId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Long sectionId) {
        return new Key(new Object[] { sectionId });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("com.lab.kot.school.model.eo.SSectionEO");
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        SequenceImpl tranSeq = new SequenceImpl("LIST_ID", this.getDBTransaction());        
        Number tNumber = tranSeq.getSequenceNumber();
        this.setSectionId(tNumber.longValue());
    }
}

