package com.lab.kot.school.model.eo;

import java.math.BigDecimal;

import java.sql.Blob;
import java.sql.Date;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Oct 02 17:46:30 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SStudentEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        SId,
        SFirstName,
        SLastName,
        SMiddleName,
        SGender,
        SNationality,
        SDateOfBitrh,
        SBirthPlace,
        SPhoto,
        SAdressLine1,
        SAdressLine2,
        SCity,
        SBloodGroup,
        SState,
        SPin,
        SCountry,
        SAddressLine3,
        SFatherName,
        SMotherName,
        SPhoneNo,
        SFamilyIncome,
        SFatherOccupation,
        SFatherQual,
        SMotherOccupation,
        SMotherQual,
        SRunningSessionEO,
        SStudentAttendanceEO;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int SID = AttributesEnum.SId.index();
    public static final int SFIRSTNAME = AttributesEnum.SFirstName.index();
    public static final int SLASTNAME = AttributesEnum.SLastName.index();
    public static final int SMIDDLENAME = AttributesEnum.SMiddleName.index();
    public static final int SGENDER = AttributesEnum.SGender.index();
    public static final int SNATIONALITY = AttributesEnum.SNationality.index();
    public static final int SDATEOFBITRH = AttributesEnum.SDateOfBitrh.index();
    public static final int SBIRTHPLACE = AttributesEnum.SBirthPlace.index();
    public static final int SPHOTO = AttributesEnum.SPhoto.index();
    public static final int SADRESSLINE1 = AttributesEnum.SAdressLine1.index();
    public static final int SADRESSLINE2 = AttributesEnum.SAdressLine2.index();
    public static final int SCITY = AttributesEnum.SCity.index();
    public static final int SBLOODGROUP = AttributesEnum.SBloodGroup.index();
    public static final int SSTATE = AttributesEnum.SState.index();
    public static final int SPIN = AttributesEnum.SPin.index();
    public static final int SCOUNTRY = AttributesEnum.SCountry.index();
    public static final int SADDRESSLINE3 = AttributesEnum.SAddressLine3.index();
    public static final int SFATHERNAME = AttributesEnum.SFatherName.index();
    public static final int SMOTHERNAME = AttributesEnum.SMotherName.index();
    public static final int SPHONENO = AttributesEnum.SPhoneNo.index();
    public static final int SFAMILYINCOME = AttributesEnum.SFamilyIncome.index();
    public static final int SFATHEROCCUPATION = AttributesEnum.SFatherOccupation.index();
    public static final int SFATHERQUAL = AttributesEnum.SFatherQual.index();
    public static final int SMOTHEROCCUPATION = AttributesEnum.SMotherOccupation.index();
    public static final int SMOTHERQUAL = AttributesEnum.SMotherQual.index();
    public static final int SRUNNINGSESSIONEO = AttributesEnum.SRunningSessionEO.index();
    public static final int SSTUDENTATTENDANCEEO = AttributesEnum.SStudentAttendanceEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SStudentEOImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("com.lab.kot.school.model.eo.SStudentEO");
    }


    /**
     * Gets the attribute value for SId, using the alias name SId.
     * @return the value of SId
     */
    public String getSId() {
        return (String) getAttributeInternal(SID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SId.
     * @param value value to set the SId
     */
    public void setSId(String value) {
        setAttributeInternal(SID, value);
    }

    /**
     * Gets the attribute value for SFirstName, using the alias name SFirstName.
     * @return the value of SFirstName
     */
    public String getSFirstName() {
        return (String) getAttributeInternal(SFIRSTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for SFirstName.
     * @param value value to set the SFirstName
     */
    public void setSFirstName(String value) {
        setAttributeInternal(SFIRSTNAME, value);
    }

    /**
     * Gets the attribute value for SLastName, using the alias name SLastName.
     * @return the value of SLastName
     */
    public String getSLastName() {
        return (String) getAttributeInternal(SLASTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for SLastName.
     * @param value value to set the SLastName
     */
    public void setSLastName(String value) {
        setAttributeInternal(SLASTNAME, value);
    }

    /**
     * Gets the attribute value for SMiddleName, using the alias name SMiddleName.
     * @return the value of SMiddleName
     */
    public String getSMiddleName() {
        return (String) getAttributeInternal(SMIDDLENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for SMiddleName.
     * @param value value to set the SMiddleName
     */
    public void setSMiddleName(String value) {
        setAttributeInternal(SMIDDLENAME, value);
    }

    /**
     * Gets the attribute value for SGender, using the alias name SGender.
     * @return the value of SGender
     */
    public String getSGender() {
        return (String) getAttributeInternal(SGENDER);
    }

    /**
     * Sets <code>value</code> as the attribute value for SGender.
     * @param value value to set the SGender
     */
    public void setSGender(String value) {
        setAttributeInternal(SGENDER, value);
    }

    /**
     * Gets the attribute value for SNationality, using the alias name SNationality.
     * @return the value of SNationality
     */
    public String getSNationality() {
        return (String) getAttributeInternal(SNATIONALITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for SNationality.
     * @param value value to set the SNationality
     */
    public void setSNationality(String value) {
        setAttributeInternal(SNATIONALITY, value);
    }

    /**
     * Gets the attribute value for SDateOfBitrh, using the alias name SDateOfBitrh.
     * @return the value of SDateOfBitrh
     */
    public Date getSDateOfBitrh() {
        return (Date) getAttributeInternal(SDATEOFBITRH);
    }

    /**
     * Sets <code>value</code> as the attribute value for SDateOfBitrh.
     * @param value value to set the SDateOfBitrh
     */
    public void setSDateOfBitrh(Date value) {
        setAttributeInternal(SDATEOFBITRH, value);
    }

    /**
     * Gets the attribute value for SBirthPlace, using the alias name SBirthPlace.
     * @return the value of SBirthPlace
     */
    public String getSBirthPlace() {
        return (String) getAttributeInternal(SBIRTHPLACE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SBirthPlace.
     * @param value value to set the SBirthPlace
     */
    public void setSBirthPlace(String value) {
        setAttributeInternal(SBIRTHPLACE, value);
    }

    /**
     * Gets the attribute value for SPhoto, using the alias name SPhoto.
     * @return the value of SPhoto
     */
    public Blob getSPhoto() {
        return (Blob) getAttributeInternal(SPHOTO);
    }

    /**
     * Sets <code>value</code> as the attribute value for SPhoto.
     * @param value value to set the SPhoto
     */
    public void setSPhoto(Blob value) {
        setAttributeInternal(SPHOTO, value);
    }

    /**
     * Gets the attribute value for SAdressLine1, using the alias name SAdressLine1.
     * @return the value of SAdressLine1
     */
    public String getSAdressLine1() {
        return (String) getAttributeInternal(SADRESSLINE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for SAdressLine1.
     * @param value value to set the SAdressLine1
     */
    public void setSAdressLine1(String value) {
        setAttributeInternal(SADRESSLINE1, value);
    }

    /**
     * Gets the attribute value for SAdressLine2, using the alias name SAdressLine2.
     * @return the value of SAdressLine2
     */
    public String getSAdressLine2() {
        return (String) getAttributeInternal(SADRESSLINE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for SAdressLine2.
     * @param value value to set the SAdressLine2
     */
    public void setSAdressLine2(String value) {
        setAttributeInternal(SADRESSLINE2, value);
    }

    /**
     * Gets the attribute value for SCity, using the alias name SCity.
     * @return the value of SCity
     */
    public String getSCity() {
        return (String) getAttributeInternal(SCITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for SCity.
     * @param value value to set the SCity
     */
    public void setSCity(String value) {
        setAttributeInternal(SCITY, value);
    }

    /**
     * Gets the attribute value for SBloodGroup, using the alias name SBloodGroup.
     * @return the value of SBloodGroup
     */
    public String getSBloodGroup() {
        return (String) getAttributeInternal(SBLOODGROUP);
    }

    /**
     * Sets <code>value</code> as the attribute value for SBloodGroup.
     * @param value value to set the SBloodGroup
     */
    public void setSBloodGroup(String value) {
        setAttributeInternal(SBLOODGROUP, value);
    }

    /**
     * Gets the attribute value for SState, using the alias name SState.
     * @return the value of SState
     */
    public String getSState() {
        return (String) getAttributeInternal(SSTATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SState.
     * @param value value to set the SState
     */
    public void setSState(String value) {
        setAttributeInternal(SSTATE, value);
    }

    /**
     * Gets the attribute value for SPin, using the alias name SPin.
     * @return the value of SPin
     */
    public String getSPin() {
        return (String) getAttributeInternal(SPIN);
    }

    /**
     * Sets <code>value</code> as the attribute value for SPin.
     * @param value value to set the SPin
     */
    public void setSPin(String value) {
        setAttributeInternal(SPIN, value);
    }

    /**
     * Gets the attribute value for SCountry, using the alias name SCountry.
     * @return the value of SCountry
     */
    public String getSCountry() {
        return (String) getAttributeInternal(SCOUNTRY);
    }

    /**
     * Sets <code>value</code> as the attribute value for SCountry.
     * @param value value to set the SCountry
     */
    public void setSCountry(String value) {
        setAttributeInternal(SCOUNTRY, value);
    }

    /**
     * Gets the attribute value for SAddressLine3, using the alias name SAddressLine3.
     * @return the value of SAddressLine3
     */
    public String getSAddressLine3() {
        return (String) getAttributeInternal(SADDRESSLINE3);
    }

    /**
     * Sets <code>value</code> as the attribute value for SAddressLine3.
     * @param value value to set the SAddressLine3
     */
    public void setSAddressLine3(String value) {
        setAttributeInternal(SADDRESSLINE3, value);
    }

    /**
     * Gets the attribute value for SFatherName, using the alias name SFatherName.
     * @return the value of SFatherName
     */
    public String getSFatherName() {
        return (String) getAttributeInternal(SFATHERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for SFatherName.
     * @param value value to set the SFatherName
     */
    public void setSFatherName(String value) {
        setAttributeInternal(SFATHERNAME, value);
    }

    /**
     * Gets the attribute value for SMotherName, using the alias name SMotherName.
     * @return the value of SMotherName
     */
    public String getSMotherName() {
        return (String) getAttributeInternal(SMOTHERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for SMotherName.
     * @param value value to set the SMotherName
     */
    public void setSMotherName(String value) {
        setAttributeInternal(SMOTHERNAME, value);
    }

    /**
     * Gets the attribute value for SPhoneNo, using the alias name SPhoneNo.
     * @return the value of SPhoneNo
     */
    public String getSPhoneNo() {
        return (String) getAttributeInternal(SPHONENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for SPhoneNo.
     * @param value value to set the SPhoneNo
     */
    public void setSPhoneNo(String value) {
        setAttributeInternal(SPHONENO, value);
    }

    /**
     * Gets the attribute value for SFamilyIncome, using the alias name SFamilyIncome.
     * @return the value of SFamilyIncome
     */
    public BigDecimal getSFamilyIncome() {
        return (BigDecimal) getAttributeInternal(SFAMILYINCOME);
    }

    /**
     * Sets <code>value</code> as the attribute value for SFamilyIncome.
     * @param value value to set the SFamilyIncome
     */
    public void setSFamilyIncome(BigDecimal value) {
        setAttributeInternal(SFAMILYINCOME, value);
    }

    /**
     * Gets the attribute value for SFatherOccupation, using the alias name SFatherOccupation.
     * @return the value of SFatherOccupation
     */
    public String getSFatherOccupation() {
        return (String) getAttributeInternal(SFATHEROCCUPATION);
    }

    /**
     * Sets <code>value</code> as the attribute value for SFatherOccupation.
     * @param value value to set the SFatherOccupation
     */
    public void setSFatherOccupation(String value) {
        setAttributeInternal(SFATHEROCCUPATION, value);
    }

    /**
     * Gets the attribute value for SFatherQual, using the alias name SFatherQual.
     * @return the value of SFatherQual
     */
    public String getSFatherQual() {
        return (String) getAttributeInternal(SFATHERQUAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for SFatherQual.
     * @param value value to set the SFatherQual
     */
    public void setSFatherQual(String value) {
        setAttributeInternal(SFATHERQUAL, value);
    }

    /**
     * Gets the attribute value for SMotherOccupation, using the alias name SMotherOccupation.
     * @return the value of SMotherOccupation
     */
    public String getSMotherOccupation() {
        return (String) getAttributeInternal(SMOTHEROCCUPATION);
    }

    /**
     * Sets <code>value</code> as the attribute value for SMotherOccupation.
     * @param value value to set the SMotherOccupation
     */
    public void setSMotherOccupation(String value) {
        setAttributeInternal(SMOTHEROCCUPATION, value);
    }

    /**
     * Gets the attribute value for SMotherQual, using the alias name SMotherQual.
     * @return the value of SMotherQual
     */
    public String getSMotherQual() {
        return (String) getAttributeInternal(SMOTHERQUAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for SMotherQual.
     * @param value value to set the SMotherQual
     */
    public void setSMotherQual(String value) {
        setAttributeInternal(SMOTHERQUAL, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getSRunningSessionEO() {
        return (RowIterator) getAttributeInternal(SRUNNINGSESSIONEO);
    }


    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getSStudentAttendanceEO() {
        return (RowIterator) getAttributeInternal(SSTUDENTATTENDANCEEO);
    }


    /**
     * @param sId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(String sId) {
        return new Key(new Object[] { sId });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        SequenceImpl tranSeq = new SequenceImpl("STUDENT_ID", this.getDBTransaction());        
        Number tNumber = tranSeq.getSequenceNumber();
        this.setSId(tNumber.stringValue());
    }
}

