CREATE TABLE S_BOOK 
(
  BOOK_ID NUMBER NOT NULL 
, ISBN VARCHAR2(20 BYTE) 
, BOOK_TITLE VARCHAR2(200 BYTE) 
, BOOK_AUTHOR VARCHAR2(200 BYTE) 
, BOOK_REMARKS VARCHAR2(400 BYTE) 
, BOOK_PUBLISH_DATE DATE 
, ACTIVE_YN VARCHAR2(1 BYTE) 
, BOOK_TYPE_CODE VARCHAR2(20 BYTE) 
, CONSTRAINT S_BOOK_PK PRIMARY KEY 
  (
    BOOK_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX S_BOOK_PK ON S_BOOK (BOOK_ID ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS;
