CREATE TABLE S_BOOK_TYPE 
(
  BOOK_TYPE_ID NUMBER NOT NULL 
, BOOK_TYPE_CODE VARCHAR2(20 BYTE) 
, BOOK_TYPE_NAME VARCHAR2(100 BYTE) 
, ACTIVE_YN VARCHAR2(1 BYTE) 
, CONSTRAINT S_BOOK_TYPE_PK PRIMARY KEY 
  (
    BOOK_TYPE_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX S_BOOK_TYPE_PK ON S_BOOK_TYPE (BOOK_TYPE_ID ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS;
