CREATE TABLE S_CLASS_TIMETABLE 
(
  T_ID VARCHAR2(20 BYTE) NOT NULL 
, SUBJECT_CODE VARCHAR2(20 BYTE) NOT NULL 
, CLASS_CODE VARCHAR2(20 BYTE) NOT NULL 
, SECTION_CODE VARCHAR2(20 BYTE) NOT NULL 
, TIME_SLOT VARCHAR2(20 BYTE) NOT NULL 
, DAYS VARCHAR2(20 BYTE) 
, SESSION_CODE VARCHAR2(20 BYTE) 
, CONSTRAINT S_CLASS_TIMETABLE_PK PRIMARY KEY 
  (
    T_ID 
  , SUBJECT_CODE 
  , CLASS_CODE 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX S_CLASS_TIMETABLE_PK ON S_CLASS_TIMETABLE (T_ID ASC, SUBJECT_CODE ASC, CLASS_CODE ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS;
