CREATE TABLE S_CLASS 
(
  CLASS_ID NUMBER NOT NULL 
, CLASS_CODE VARCHAR2(20 BYTE) NOT NULL 
, CLASS_NAME VARCHAR2(100 BYTE) NOT NULL 
, ACTIVE_YN VARCHAR2(1 BYTE) 
, CONSTRAINT S_CLASS_PK PRIMARY KEY 
  (
    CLASS_ID 
  , CLASS_CODE 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX S_CLASS_PK ON S_CLASS (CLASS_ID ASC, CLASS_CODE ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS;
