CREATE TABLE S_COMMON_LOOKUP 
(
  LOV_ID NUMBER NOT NULL 
, LOV_FIELD_NAME VARCHAR2(50 BYTE) NOT NULL 
, LOV_FIELD_VALUE VARCHAR2(50 BYTE) 
, LOV_SHORT_NAME VARCHAR2(50 BYTE) 
, LOV_ACTIVE_YN VARCHAR2(2 BYTE) 
, LOV_LONG_NAME VARCHAR2(100 BYTE) 
, CONSTRAINT S_COMMON_LOOKUP_PK PRIMARY KEY 
  (
    LOV_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX S_COMMON_LOOKUP_PK ON S_COMMON_LOOKUP (LOV_ID ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS;
