CREATE TABLE S_EXAM_TIME_TABLE 
(
  S_DATE DATE 
, S_DAY VARCHAR2(20 BYTE) 
, SUBJECT_CODE VARCHAR2(20 BYTE) NOT NULL 
, PAPER_CODE VARCHAR2(20 BYTE) NOT NULL 
, CLASS_CODE VARCHAR2(20 BYTE) NOT NULL 
, EXAM_TYPE VARCHAR2(20 BYTE) NOT NULL 
, TIME_SLOT_FROM VARCHAR2(20 BYTE) 
, TIME_SLOT_TO VARCHAR2(20 BYTE) 
, SESSION_CODE VARCHAR2(20 BYTE) NOT NULL 
, CONSTRAINT S_EXAM_TIME_TABLE_PK PRIMARY KEY 
  (
    SUBJECT_CODE 
  , CLASS_CODE 
  , SESSION_CODE 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX S_EXAM_TIME_TABLE_PK ON S_EXAM_TIME_TABLE (SUBJECT_CODE ASC, CLASS_CODE ASC, SESSION_CODE ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS;
