CREATE TABLE S_SESSION 
(
  SESSION_ID NUMBER(10, 0) NOT NULL 
, SESSION_NAME VARCHAR2(20 BYTE) NOT NULL 
, SESSION_START_DATE DATE NOT NULL 
, SESSION_CODE VARCHAR2(20 BYTE) NOT NULL 
, SESSION_END_DATE DATE NOT NULL 
, ACTIVE_YN VARCHAR2(1 BYTE) 
, CONSTRAINT S_SESSION_PK PRIMARY KEY 
  (
    SESSION_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX S_SESSION_PK ON S_SESSION (SESSION_ID ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS;
