CREATE TABLE S_STUDENT 
(
  S_ID VARCHAR2(20 BYTE) NOT NULL 
, S_FIRST_NAME VARCHAR2(50 BYTE) NOT NULL 
, S_LAST_NAME VARCHAR2(50 BYTE) NOT NULL 
, S_MIDDLE_NAME VARCHAR2(50 BYTE) NOT NULL 
, S_GENDER VARCHAR2(1 BYTE) NOT NULL 
, S_NATIONALITY VARCHAR2(20 BYTE) NOT NULL 
, S_DATE_OF_BITRH DATE NOT NULL 
, S_BIRTH_PLACE VARCHAR2(50 BYTE) NOT NULL 
, S_PHOTO BLOB NOT NULL 
, S_ADRESS_LINE1 VARCHAR2(50 BYTE) NOT NULL 
, S_ADRESS_LINE2 VARCHAR2(50 BYTE) NOT NULL 
, S_CITY VARCHAR2(20 BYTE) NOT NULL 
, S_BLOOD_GROUP VARCHAR2(20 BYTE) NOT NULL 
, S_STATE VARCHAR2(50 BYTE) 
, S_PIN VARCHAR2(20 BYTE) 
, S_COUNTRY VARCHAR2(20 BYTE) 
, S_ADDRESS_LINE3 VARCHAR2(50 BYTE) 
, S_FATHER_NAME VARCHAR2(100 BYTE) 
, S_MOTHER_NAME VARCHAR2(100 BYTE) 
, S_PHONE_NO VARCHAR2(20 BYTE) 
, S_FAMILY_INCOME NUMBER 
, S_FATHER_OCCUPATION VARCHAR2(20 BYTE) 
, S_FATHER_QUAL VARCHAR2(20 BYTE) 
, S_MOTHER_OCCUPATION VARCHAR2(20 BYTE) 
, S_MOTHER_QUAL VARCHAR2(20 BYTE) 
, CONSTRAINT S_STUDENT_PK PRIMARY KEY 
  (
    S_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX S_STUDENT_PK ON S_STUDENT (S_ID ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
LOB (S_PHOTO) STORE AS SYS_LOB0000026524C00009$$ 
( 
  ENABLE STORAGE IN ROW 
  CHUNK 8192 
  RETENTION 
  NOCACHE 
  LOGGING 
  TABLESPACE SYSTEM 
  STORAGE 
  ( 
    INITIAL 65536 
    NEXT 1048576 
    MINEXTENTS 1 
    MAXEXTENTS UNLIMITED 
    FREELISTS 1 
    FREELIST GROUPS 1 
    BUFFER_POOL DEFAULT 
  )  
);
