CREATE TABLE S_STUD_ATTEND 
(
  S_ID VARCHAR2(20 BYTE) NOT NULL 
, CLASS_CODE VARCHAR2(20 BYTE) NOT NULL 
, SECTION_CODE VARCHAR2(20 BYTE) NOT NULL 
, SESSION_CODE VARCHAR2(20 BYTE) NOT NULL 
, MONTH VARCHAR2(20 BYTE) NOT NULL 
, YEAR NUMBER 
, D_1 VARCHAR2(1 BYTE) 
, D_2 VARCHAR2(1 BYTE) 
, D_3 VARCHAR2(1 BYTE) 
, D_4 VARCHAR2(1 BYTE) 
, D_5 VARCHAR2(1 BYTE) 
, D_6 VARCHAR2(1 BYTE) 
, D_7 VARCHAR2(1 BYTE) 
, D_8 VARCHAR2(1 BYTE) 
, D_9 VARCHAR2(1 BYTE) 
, D_10 VARCHAR2(1 BYTE) 
, D_11 VARCHAR2(1 BYTE) 
, D_12 VARCHAR2(1 BYTE) 
, D_13 VARCHAR2(1 BYTE) 
, D_14 VARCHAR2(1 BYTE) 
, D_15 VARCHAR2(1 BYTE) 
, D_16 VARCHAR2(1 BYTE) 
, D_17 VARCHAR2(1 BYTE) 
, D_18 VARCHAR2(1 BYTE) 
, D_19 VARCHAR2(1 BYTE) 
, D_20 VARCHAR2(1 BYTE) 
, D_21 VARCHAR2(1 BYTE) 
, D_22 VARCHAR2(1 BYTE) 
, D_23 VARCHAR2(1 BYTE) 
, D_24 VARCHAR2(1 BYTE) 
, D_25 VARCHAR2(1 BYTE) 
, D_26 VARCHAR2(1 BYTE) 
, D_27 VARCHAR2(1 BYTE) 
, D_28 VARCHAR2(1 BYTE) 
, D_29 VARCHAR2(1 BYTE) 
, D_30 VARCHAR2(1 BYTE) 
, D_31 VARCHAR2(1 BYTE) 
, CONSTRAINT S_STUD_ATTEND_PK PRIMARY KEY 
  (
    S_ID 
  , MONTH 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX S_STUD_ATTEND_IDX ON S_STUD_ATTEND (S_ID ASC, MONTH ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS;
