CREATE TABLE S_SUBJECTS 
(
  SUBJECT_ID NUMBER NOT NULL 
, SUBJECT_NAME VARCHAR2(100 BYTE) 
, SUBJECT_CODE VARCHAR2(20 BYTE) 
, SUBJECT_DESC VARCHAR2(400 BYTE) 
, ACTIVE_YN VARCHAR2(1 BYTE) 
, CONSTRAINT S_SUBJECTS_PK PRIMARY KEY 
  (
    SUBJECT_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX S_SUBJECTS_PK ON S_SUBJECTS (SUBJECT_ID ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS;
