CREATE TABLE S_TEACHER_ATTENDANCE 
(
  T_ID VARCHAR2(20 BYTE) NOT NULL 
, ATTENDANCE_DATE DATE NOT NULL 
, ATTENDANCE_FLAG VARCHAR2(1 BYTE) 
, LATE_FLAG VARCHAR2(1 BYTE) 
, HOLIDAY_FLAG VARCHAR2(1 BYTE) 
, CONSTRAINT S_TEACHER_ATTENDANCE_PK PRIMARY KEY 
  (
    T_ID 
  , ATTENDANCE_DATE 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX S_TEACHER_ATTENDANCE_PK ON S_TEACHER_ATTENDANCE (T_ID ASC, ATTENDANCE_DATE ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS;
