CREATE TABLE S_TIME_TABLE 
(
  MONDAY VARCHAR2(50 BYTE) 
, TUESDAY VARCHAR2(50 BYTE) 
, WEDNESDAY VARCHAR2(50 BYTE) 
, THURSDAY VARCHAR2(50 BYTE) 
, FRIDAY VARCHAR2(50 BYTE) 
, SATURDAY VARCHAR2(50 BYTE) 
, SUNDAY VARCHAR2(50 BYTE) 
, T_ID VARCHAR2(20 BYTE) NOT NULL 
, CLASS_CODE VARCHAR2(20 BYTE) NOT NULL 
, SECTION_CODE VARCHAR2(20 BYTE) NOT NULL 
, SESSION_CODE VARCHAR2(20 BYTE) NOT NULL 
, SUBJECT_CODE VARCHAR2(20 BYTE) NOT NULL 
, TIME_SLOT VARCHAR2(20 BYTE) 
, CONSTRAINT S_TIME_TABLE_PK PRIMARY KEY 
  (
    CLASS_CODE 
  , SECTION_CODE 
  , SESSION_CODE 
  , SUBJECT_CODE 
  , T_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX S_TIME_TABLE_PK ON S_TIME_TABLE (CLASS_CODE ASC, SECTION_CODE ASC, SESSION_CODE ASC, SUBJECT_CODE ASC, T_ID ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS;
