package com.lab.kot.school.model.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Oct 14 23:53:34 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BookBasketVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public BookBasketVOImpl() {
    }
}

