package com.lab.kot.school.model.vo;

import com.lab.kot.school.model.vo.common.SBookAllocationVO;

import oracle.jbo.Row;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Oct 15 01:19:03 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SBookAllocationVOImpl extends ViewObjectImpl implements SBookAllocationVO {
    /**
     * This is the default constructor (do not remove).
     */
    public SBookAllocationVOImpl() {
    }
    public void createInit(Long bookId) {
        if(bookId != null)
        {
            Row nRow = this.createRow();
            nRow.setAttribute("BookId", bookId);
            this.insertRow(nRow);
        }
    }
}

