package com.lab.kot.school.model.vo;

import com.lab.kot.school.model.eo.SStudentEOImpl;

import java.math.BigDecimal;

import java.sql.Blob;
import java.sql.Date;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Oct 02 18:03:07 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SStudentVORowImpl extends ViewRowImpl {
    public static final int ENTITY_SSTUDENTEO = 0;
    public static final int ENTITY_SRUNNINGSESSIONEO = 1;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        SId,
        SFirstName,
        SLastName,
        SMiddleName,
        SGender,
        SNationality,
        SDateOfBitrh,
        SBirthPlace,
        SPhoto,
        SAdressLine1,
        SAdressLine2,
        SCity,
        SBloodGroup,
        SState,
        SPin,
        SCountry,
        SAddressLine3,
        SFatherName,
        SMotherName,
        SPhoneNo,
        SFamilyIncome,
        SFatherOccupation,
        SFatherQual,
        SMotherOccupation,
        SMotherQual,
        SId1,
        ClassCode,
        SectionCode,
        SessionCode,
        RollNo,
        PromotionFlag,
        SRunningSessionVO,
        SClassVA,
        SSectionVA,
        SSessionVA;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int SID = AttributesEnum.SId.index();
    public static final int SFIRSTNAME = AttributesEnum.SFirstName.index();
    public static final int SLASTNAME = AttributesEnum.SLastName.index();
    public static final int SMIDDLENAME = AttributesEnum.SMiddleName.index();
    public static final int SGENDER = AttributesEnum.SGender.index();
    public static final int SNATIONALITY = AttributesEnum.SNationality.index();
    public static final int SDATEOFBITRH = AttributesEnum.SDateOfBitrh.index();
    public static final int SBIRTHPLACE = AttributesEnum.SBirthPlace.index();
    public static final int SPHOTO = AttributesEnum.SPhoto.index();
    public static final int SADRESSLINE1 = AttributesEnum.SAdressLine1.index();
    public static final int SADRESSLINE2 = AttributesEnum.SAdressLine2.index();
    public static final int SCITY = AttributesEnum.SCity.index();
    public static final int SBLOODGROUP = AttributesEnum.SBloodGroup.index();
    public static final int SSTATE = AttributesEnum.SState.index();
    public static final int SPIN = AttributesEnum.SPin.index();
    public static final int SCOUNTRY = AttributesEnum.SCountry.index();
    public static final int SADDRESSLINE3 = AttributesEnum.SAddressLine3.index();
    public static final int SFATHERNAME = AttributesEnum.SFatherName.index();
    public static final int SMOTHERNAME = AttributesEnum.SMotherName.index();
    public static final int SPHONENO = AttributesEnum.SPhoneNo.index();
    public static final int SFAMILYINCOME = AttributesEnum.SFamilyIncome.index();
    public static final int SFATHEROCCUPATION = AttributesEnum.SFatherOccupation.index();
    public static final int SFATHERQUAL = AttributesEnum.SFatherQual.index();
    public static final int SMOTHEROCCUPATION = AttributesEnum.SMotherOccupation.index();
    public static final int SMOTHERQUAL = AttributesEnum.SMotherQual.index();
    public static final int SID1 = AttributesEnum.SId1.index();
    public static final int CLASSCODE = AttributesEnum.ClassCode.index();
    public static final int SECTIONCODE = AttributesEnum.SectionCode.index();
    public static final int SESSIONCODE = AttributesEnum.SessionCode.index();
    public static final int ROLLNO = AttributesEnum.RollNo.index();
    public static final int PROMOTIONFLAG = AttributesEnum.PromotionFlag.index();
    public static final int SRUNNINGSESSIONVO = AttributesEnum.SRunningSessionVO.index();
    public static final int SCLASSVA = AttributesEnum.SClassVA.index();
    public static final int SSECTIONVA = AttributesEnum.SSectionVA.index();
    public static final int SSESSIONVA = AttributesEnum.SSessionVA.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SStudentVORowImpl() {
    }

    /**
     * Gets SStudentEO entity object.
     * @return the SStudentEO
     */
    public SStudentEOImpl getSStudentEO() {
        return (SStudentEOImpl) getEntity(ENTITY_SSTUDENTEO);
    }

    /**
     * Gets SRunningSessionEO entity object.
     * @return the SRunningSessionEO
     */
    public EntityImpl getSRunningSessionEO() {
        return (EntityImpl) getEntity(ENTITY_SRUNNINGSESSIONEO);
    }

    /**
     * Gets the attribute value for S_ID using the alias name SId.
     * @return the S_ID
     */
    public String getSId() {
        return (String) getAttributeInternal(SID);
    }

    /**
     * Sets <code>value</code> as attribute value for S_ID using the alias name SId.
     * @param value value to set the S_ID
     */
    public void setSId(String value) {
        setAttributeInternal(SID, value);
    }

    /**
     * Gets the attribute value for S_FIRST_NAME using the alias name SFirstName.
     * @return the S_FIRST_NAME
     */
    public String getSFirstName() {
        return (String) getAttributeInternal(SFIRSTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for S_FIRST_NAME using the alias name SFirstName.
     * @param value value to set the S_FIRST_NAME
     */
    public void setSFirstName(String value) {
        setAttributeInternal(SFIRSTNAME, value);
    }

    /**
     * Gets the attribute value for S_LAST_NAME using the alias name SLastName.
     * @return the S_LAST_NAME
     */
    public String getSLastName() {
        return (String) getAttributeInternal(SLASTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for S_LAST_NAME using the alias name SLastName.
     * @param value value to set the S_LAST_NAME
     */
    public void setSLastName(String value) {
        setAttributeInternal(SLASTNAME, value);
    }

    /**
     * Gets the attribute value for S_MIDDLE_NAME using the alias name SMiddleName.
     * @return the S_MIDDLE_NAME
     */
    public String getSMiddleName() {
        return (String) getAttributeInternal(SMIDDLENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for S_MIDDLE_NAME using the alias name SMiddleName.
     * @param value value to set the S_MIDDLE_NAME
     */
    public void setSMiddleName(String value) {
        setAttributeInternal(SMIDDLENAME, value);
    }

    /**
     * Gets the attribute value for S_GENDER using the alias name SGender.
     * @return the S_GENDER
     */
    public String getSGender() {
        return (String) getAttributeInternal(SGENDER);
    }

    /**
     * Sets <code>value</code> as attribute value for S_GENDER using the alias name SGender.
     * @param value value to set the S_GENDER
     */
    public void setSGender(String value) {
        setAttributeInternal(SGENDER, value);
    }

    /**
     * Gets the attribute value for S_NATIONALITY using the alias name SNationality.
     * @return the S_NATIONALITY
     */
    public String getSNationality() {
        return (String) getAttributeInternal(SNATIONALITY);
    }

    /**
     * Sets <code>value</code> as attribute value for S_NATIONALITY using the alias name SNationality.
     * @param value value to set the S_NATIONALITY
     */
    public void setSNationality(String value) {
        setAttributeInternal(SNATIONALITY, value);
    }

    /**
     * Gets the attribute value for S_DATE_OF_BITRH using the alias name SDateOfBitrh.
     * @return the S_DATE_OF_BITRH
     */
    public Date getSDateOfBitrh() {
        return (Date) getAttributeInternal(SDATEOFBITRH);
    }

    /**
     * Sets <code>value</code> as attribute value for S_DATE_OF_BITRH using the alias name SDateOfBitrh.
     * @param value value to set the S_DATE_OF_BITRH
     */
    public void setSDateOfBitrh(Date value) {
        setAttributeInternal(SDATEOFBITRH, value);
    }

    /**
     * Gets the attribute value for S_BIRTH_PLACE using the alias name SBirthPlace.
     * @return the S_BIRTH_PLACE
     */
    public String getSBirthPlace() {
        return (String) getAttributeInternal(SBIRTHPLACE);
    }

    /**
     * Sets <code>value</code> as attribute value for S_BIRTH_PLACE using the alias name SBirthPlace.
     * @param value value to set the S_BIRTH_PLACE
     */
    public void setSBirthPlace(String value) {
        setAttributeInternal(SBIRTHPLACE, value);
    }

    /**
     * Gets the attribute value for S_PHOTO using the alias name SPhoto.
     * @return the S_PHOTO
     */
    public Blob getSPhoto() {
        return (Blob) getAttributeInternal(SPHOTO);
    }

    /**
     * Sets <code>value</code> as attribute value for S_PHOTO using the alias name SPhoto.
     * @param value value to set the S_PHOTO
     */
    public void setSPhoto(Blob value) {
        setAttributeInternal(SPHOTO, value);
    }

    /**
     * Gets the attribute value for S_ADRESS_LINE1 using the alias name SAdressLine1.
     * @return the S_ADRESS_LINE1
     */
    public String getSAdressLine1() {
        return (String) getAttributeInternal(SADRESSLINE1);
    }

    /**
     * Sets <code>value</code> as attribute value for S_ADRESS_LINE1 using the alias name SAdressLine1.
     * @param value value to set the S_ADRESS_LINE1
     */
    public void setSAdressLine1(String value) {
        setAttributeInternal(SADRESSLINE1, value);
    }

    /**
     * Gets the attribute value for S_ADRESS_LINE2 using the alias name SAdressLine2.
     * @return the S_ADRESS_LINE2
     */
    public String getSAdressLine2() {
        return (String) getAttributeInternal(SADRESSLINE2);
    }

    /**
     * Sets <code>value</code> as attribute value for S_ADRESS_LINE2 using the alias name SAdressLine2.
     * @param value value to set the S_ADRESS_LINE2
     */
    public void setSAdressLine2(String value) {
        setAttributeInternal(SADRESSLINE2, value);
    }

    /**
     * Gets the attribute value for S_CITY using the alias name SCity.
     * @return the S_CITY
     */
    public String getSCity() {
        return (String) getAttributeInternal(SCITY);
    }

    /**
     * Sets <code>value</code> as attribute value for S_CITY using the alias name SCity.
     * @param value value to set the S_CITY
     */
    public void setSCity(String value) {
        setAttributeInternal(SCITY, value);
    }

    /**
     * Gets the attribute value for S_BLOOD_GROUP using the alias name SBloodGroup.
     * @return the S_BLOOD_GROUP
     */
    public String getSBloodGroup() {
        return (String) getAttributeInternal(SBLOODGROUP);
    }

    /**
     * Sets <code>value</code> as attribute value for S_BLOOD_GROUP using the alias name SBloodGroup.
     * @param value value to set the S_BLOOD_GROUP
     */
    public void setSBloodGroup(String value) {
        setAttributeInternal(SBLOODGROUP, value);
    }

    /**
     * Gets the attribute value for S_STATE using the alias name SState.
     * @return the S_STATE
     */
    public String getSState() {
        return (String) getAttributeInternal(SSTATE);
    }

    /**
     * Sets <code>value</code> as attribute value for S_STATE using the alias name SState.
     * @param value value to set the S_STATE
     */
    public void setSState(String value) {
        setAttributeInternal(SSTATE, value);
    }

    /**
     * Gets the attribute value for S_PIN using the alias name SPin.
     * @return the S_PIN
     */
    public String getSPin() {
        return (String) getAttributeInternal(SPIN);
    }

    /**
     * Sets <code>value</code> as attribute value for S_PIN using the alias name SPin.
     * @param value value to set the S_PIN
     */
    public void setSPin(String value) {
        setAttributeInternal(SPIN, value);
    }

    /**
     * Gets the attribute value for S_COUNTRY using the alias name SCountry.
     * @return the S_COUNTRY
     */
    public String getSCountry() {
        return (String) getAttributeInternal(SCOUNTRY);
    }

    /**
     * Sets <code>value</code> as attribute value for S_COUNTRY using the alias name SCountry.
     * @param value value to set the S_COUNTRY
     */
    public void setSCountry(String value) {
        setAttributeInternal(SCOUNTRY, value);
    }

    /**
     * Gets the attribute value for S_ADDRESS_LINE3 using the alias name SAddressLine3.
     * @return the S_ADDRESS_LINE3
     */
    public String getSAddressLine3() {
        return (String) getAttributeInternal(SADDRESSLINE3);
    }

    /**
     * Sets <code>value</code> as attribute value for S_ADDRESS_LINE3 using the alias name SAddressLine3.
     * @param value value to set the S_ADDRESS_LINE3
     */
    public void setSAddressLine3(String value) {
        setAttributeInternal(SADDRESSLINE3, value);
    }

    /**
     * Gets the attribute value for S_FATHER_NAME using the alias name SFatherName.
     * @return the S_FATHER_NAME
     */
    public String getSFatherName() {
        return (String) getAttributeInternal(SFATHERNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for S_FATHER_NAME using the alias name SFatherName.
     * @param value value to set the S_FATHER_NAME
     */
    public void setSFatherName(String value) {
        setAttributeInternal(SFATHERNAME, value);
    }

    /**
     * Gets the attribute value for S_MOTHER_NAME using the alias name SMotherName.
     * @return the S_MOTHER_NAME
     */
    public String getSMotherName() {
        return (String) getAttributeInternal(SMOTHERNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for S_MOTHER_NAME using the alias name SMotherName.
     * @param value value to set the S_MOTHER_NAME
     */
    public void setSMotherName(String value) {
        setAttributeInternal(SMOTHERNAME, value);
    }

    /**
     * Gets the attribute value for S_PHONE_NO using the alias name SPhoneNo.
     * @return the S_PHONE_NO
     */
    public String getSPhoneNo() {
        return (String) getAttributeInternal(SPHONENO);
    }

    /**
     * Sets <code>value</code> as attribute value for S_PHONE_NO using the alias name SPhoneNo.
     * @param value value to set the S_PHONE_NO
     */
    public void setSPhoneNo(String value) {
        setAttributeInternal(SPHONENO, value);
    }

    /**
     * Gets the attribute value for S_FAMILY_INCOME using the alias name SFamilyIncome.
     * @return the S_FAMILY_INCOME
     */
    public BigDecimal getSFamilyIncome() {
        return (BigDecimal) getAttributeInternal(SFAMILYINCOME);
    }

    /**
     * Sets <code>value</code> as attribute value for S_FAMILY_INCOME using the alias name SFamilyIncome.
     * @param value value to set the S_FAMILY_INCOME
     */
    public void setSFamilyIncome(BigDecimal value) {
        setAttributeInternal(SFAMILYINCOME, value);
    }

    /**
     * Gets the attribute value for S_FATHER_OCCUPATION using the alias name SFatherOccupation.
     * @return the S_FATHER_OCCUPATION
     */
    public String getSFatherOccupation() {
        return (String) getAttributeInternal(SFATHEROCCUPATION);
    }

    /**
     * Sets <code>value</code> as attribute value for S_FATHER_OCCUPATION using the alias name SFatherOccupation.
     * @param value value to set the S_FATHER_OCCUPATION
     */
    public void setSFatherOccupation(String value) {
        setAttributeInternal(SFATHEROCCUPATION, value);
    }

    /**
     * Gets the attribute value for S_FATHER_QUAL using the alias name SFatherQual.
     * @return the S_FATHER_QUAL
     */
    public String getSFatherQual() {
        return (String) getAttributeInternal(SFATHERQUAL);
    }

    /**
     * Sets <code>value</code> as attribute value for S_FATHER_QUAL using the alias name SFatherQual.
     * @param value value to set the S_FATHER_QUAL
     */
    public void setSFatherQual(String value) {
        setAttributeInternal(SFATHERQUAL, value);
    }

    /**
     * Gets the attribute value for S_MOTHER_OCCUPATION using the alias name SMotherOccupation.
     * @return the S_MOTHER_OCCUPATION
     */
    public String getSMotherOccupation() {
        return (String) getAttributeInternal(SMOTHEROCCUPATION);
    }

    /**
     * Sets <code>value</code> as attribute value for S_MOTHER_OCCUPATION using the alias name SMotherOccupation.
     * @param value value to set the S_MOTHER_OCCUPATION
     */
    public void setSMotherOccupation(String value) {
        setAttributeInternal(SMOTHEROCCUPATION, value);
    }

    /**
     * Gets the attribute value for S_MOTHER_QUAL using the alias name SMotherQual.
     * @return the S_MOTHER_QUAL
     */
    public String getSMotherQual() {
        return (String) getAttributeInternal(SMOTHERQUAL);
    }

    /**
     * Sets <code>value</code> as attribute value for S_MOTHER_QUAL using the alias name SMotherQual.
     * @param value value to set the S_MOTHER_QUAL
     */
    public void setSMotherQual(String value) {
        setAttributeInternal(SMOTHERQUAL, value);
    }

    /**
     * Gets the attribute value for S_ID using the alias name SId1.
     * @return the S_ID
     */
    public String getSId1() {
        return (String) getAttributeInternal(SID1);
    }

    /**
     * Sets <code>value</code> as attribute value for S_ID using the alias name SId1.
     * @param value value to set the S_ID
     */
    public void setSId1(String value) {
        setAttributeInternal(SID1, value);
    }

    /**
     * Gets the attribute value for CLASS_CODE using the alias name ClassCode.
     * @return the CLASS_CODE
     */
    public String getClassCode() {
        return (String) getAttributeInternal(CLASSCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for CLASS_CODE using the alias name ClassCode.
     * @param value value to set the CLASS_CODE
     */
    public void setClassCode(String value) {
        setAttributeInternal(CLASSCODE, value);
    }

    /**
     * Gets the attribute value for SECTION_CODE using the alias name SectionCode.
     * @return the SECTION_CODE
     */
    public String getSectionCode() {
        return (String) getAttributeInternal(SECTIONCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for SECTION_CODE using the alias name SectionCode.
     * @param value value to set the SECTION_CODE
     */
    public void setSectionCode(String value) {
        setAttributeInternal(SECTIONCODE, value);
    }

    /**
     * Gets the attribute value for SESSION_CODE using the alias name SessionCode.
     * @return the SESSION_CODE
     */
    public String getSessionCode() {
        return (String) getAttributeInternal(SESSIONCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for SESSION_CODE using the alias name SessionCode.
     * @param value value to set the SESSION_CODE
     */
    public void setSessionCode(String value) {
        setAttributeInternal(SESSIONCODE, value);
    }

    /**
     * Gets the attribute value for ROLL_NO using the alias name RollNo.
     * @return the ROLL_NO
     */
    public Long getRollNo() {
        return (Long) getAttributeInternal(ROLLNO);
    }

    /**
     * Sets <code>value</code> as attribute value for ROLL_NO using the alias name RollNo.
     * @param value value to set the ROLL_NO
     */
    public void setRollNo(Long value) {
        setAttributeInternal(ROLLNO, value);
    }

    /**
     * Gets the attribute value for PROMOTION_FLAG using the alias name PromotionFlag.
     * @return the PROMOTION_FLAG
     */
    public String getPromotionFlag() {
        return (String) getAttributeInternal(PROMOTIONFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for PROMOTION_FLAG using the alias name PromotionFlag.
     * @param value value to set the PROMOTION_FLAG
     */
    public void setPromotionFlag(String value) {
        setAttributeInternal(PROMOTIONFLAG, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link SRunningSessionVO.
     */
    public RowIterator getSRunningSessionVO() {
        return (RowIterator) getAttributeInternal(SRUNNINGSESSIONVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SClassVA.
     */
    public RowSet getSClassVA() {
        return (RowSet) getAttributeInternal(SCLASSVA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SSectionVA.
     */
    public RowSet getSSectionVA() {
        return (RowSet) getAttributeInternal(SSECTIONVA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SSessionVA.
     */
    public RowSet getSSessionVA() {
        return (RowSet) getAttributeInternal(SSESSIONVA);
    }
}

