package com.lab.kot.school.model.vo;

import oracle.jbo.RowSet;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 12 23:19:02 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SStudAttendVORowImpl extends ViewRowImpl {


    public static final int ENTITY_SSTUDATTENDEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        SId,
        ClassCode,
        SectionCode,
        SessionCode,
        Month,
        Year,
        D1,
        D2,
        D3,
        D4,
        D5,
        D6,
        D7,
        D8,
        D9,
        D10,
        D11,
        D12,
        D13,
        D14,
        D15,
        D16,
        D17,
        D18,
        D19,
        D20,
        D21,
        D22,
        D23,
        D24,
        D25,
        D26,
        D27,
        D28,
        D29,
        D30,
        D31,
        Total,
        SCommonLookupVA,
        SSectionVA,
        SSessionVA,
        SClassVA;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int SID = AttributesEnum.SId.index();
    public static final int CLASSCODE = AttributesEnum.ClassCode.index();
    public static final int SECTIONCODE = AttributesEnum.SectionCode.index();
    public static final int SESSIONCODE = AttributesEnum.SessionCode.index();
    public static final int MONTH = AttributesEnum.Month.index();
    public static final int YEAR = AttributesEnum.Year.index();
    public static final int D1 = AttributesEnum.D1.index();
    public static final int D2 = AttributesEnum.D2.index();
    public static final int D3 = AttributesEnum.D3.index();
    public static final int D4 = AttributesEnum.D4.index();
    public static final int D5 = AttributesEnum.D5.index();
    public static final int D6 = AttributesEnum.D6.index();
    public static final int D7 = AttributesEnum.D7.index();
    public static final int D8 = AttributesEnum.D8.index();
    public static final int D9 = AttributesEnum.D9.index();
    public static final int D10 = AttributesEnum.D10.index();
    public static final int D11 = AttributesEnum.D11.index();
    public static final int D12 = AttributesEnum.D12.index();
    public static final int D13 = AttributesEnum.D13.index();
    public static final int D14 = AttributesEnum.D14.index();
    public static final int D15 = AttributesEnum.D15.index();
    public static final int D16 = AttributesEnum.D16.index();
    public static final int D17 = AttributesEnum.D17.index();
    public static final int D18 = AttributesEnum.D18.index();
    public static final int D19 = AttributesEnum.D19.index();
    public static final int D20 = AttributesEnum.D20.index();
    public static final int D21 = AttributesEnum.D21.index();
    public static final int D22 = AttributesEnum.D22.index();
    public static final int D23 = AttributesEnum.D23.index();
    public static final int D24 = AttributesEnum.D24.index();
    public static final int D25 = AttributesEnum.D25.index();
    public static final int D26 = AttributesEnum.D26.index();
    public static final int D27 = AttributesEnum.D27.index();
    public static final int D28 = AttributesEnum.D28.index();
    public static final int D29 = AttributesEnum.D29.index();
    public static final int D30 = AttributesEnum.D30.index();
    public static final int D31 = AttributesEnum.D31.index();
    public static final int TOTAL = AttributesEnum.Total.index();
    public static final int SCOMMONLOOKUPVA = AttributesEnum.SCommonLookupVA.index();
    public static final int SSECTIONVA = AttributesEnum.SSectionVA.index();
    public static final int SSESSIONVA = AttributesEnum.SSessionVA.index();
    public static final int SCLASSVA = AttributesEnum.SClassVA.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SStudAttendVORowImpl() {
    }

    /**
     * Gets SStudAttendEO entity object.
     * @return the SStudAttendEO
     */
    public EntityImpl getSStudAttendEO() {
        return (EntityImpl) getEntity(ENTITY_SSTUDATTENDEO);
    }

    /**
     * Gets the attribute value for S_ID using the alias name SId.
     * @return the S_ID
     */
    public String getSId() {
        return (String) getAttributeInternal(SID);
    }

    /**
     * Sets <code>value</code> as attribute value for S_ID using the alias name SId.
     * @param value value to set the S_ID
     */
    public void setSId(String value) {
        setAttributeInternal(SID, value);
    }

    /**
     * Gets the attribute value for CLASS_CODE using the alias name ClassCode.
     * @return the CLASS_CODE
     */
    public String getClassCode() {
        return (String) getAttributeInternal(CLASSCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for CLASS_CODE using the alias name ClassCode.
     * @param value value to set the CLASS_CODE
     */
    public void setClassCode(String value) {
        setAttributeInternal(CLASSCODE, value);
    }

    /**
     * Gets the attribute value for SECTION_CODE using the alias name SectionCode.
     * @return the SECTION_CODE
     */
    public String getSectionCode() {
        return (String) getAttributeInternal(SECTIONCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for SECTION_CODE using the alias name SectionCode.
     * @param value value to set the SECTION_CODE
     */
    public void setSectionCode(String value) {
        setAttributeInternal(SECTIONCODE, value);
    }

    /**
     * Gets the attribute value for SESSION_CODE using the alias name SessionCode.
     * @return the SESSION_CODE
     */
    public String getSessionCode() {
        return (String) getAttributeInternal(SESSIONCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for SESSION_CODE using the alias name SessionCode.
     * @param value value to set the SESSION_CODE
     */
    public void setSessionCode(String value) {
        setAttributeInternal(SESSIONCODE, value);
    }

    /**
     * Gets the attribute value for MONTH using the alias name Month.
     * @return the MONTH
     */
    public String getMonth() {
        return (String) getAttributeInternal(MONTH);
    }

    /**
     * Sets <code>value</code> as attribute value for MONTH using the alias name Month.
     * @param value value to set the MONTH
     */
    public void setMonth(String value) {
        setAttributeInternal(MONTH, value);
    }

    /**
     * Gets the attribute value for YEAR using the alias name Year.
     * @return the YEAR
     */
    public Integer getYear() {
        return (Integer) getAttributeInternal(YEAR);
    }

    /**
     * Sets <code>value</code> as attribute value for YEAR using the alias name Year.
     * @param value value to set the YEAR
     */
    public void setYear(Integer value) {
        setAttributeInternal(YEAR, value);
    }

    /**
     * Gets the attribute value for D_1 using the alias name D1.
     * @return the D_1
     */
    public String getD1() {
        return (String) getAttributeInternal(D1);
    }

    /**
     * Sets <code>value</code> as attribute value for D_1 using the alias name D1.
     * @param value value to set the D_1
     */
    public void setD1(String value) {
        setAttributeInternal(D1, value);
    }

    /**
     * Gets the attribute value for D_2 using the alias name D2.
     * @return the D_2
     */
    public String getD2() {
        return (String) getAttributeInternal(D2);
    }

    /**
     * Sets <code>value</code> as attribute value for D_2 using the alias name D2.
     * @param value value to set the D_2
     */
    public void setD2(String value) {
        setAttributeInternal(D2, value);
    }

    /**
     * Gets the attribute value for D_3 using the alias name D3.
     * @return the D_3
     */
    public String getD3() {
        return (String) getAttributeInternal(D3);
    }

    /**
     * Sets <code>value</code> as attribute value for D_3 using the alias name D3.
     * @param value value to set the D_3
     */
    public void setD3(String value) {
        setAttributeInternal(D3, value);
    }

    /**
     * Gets the attribute value for D_4 using the alias name D4.
     * @return the D_4
     */
    public String getD4() {
        return (String) getAttributeInternal(D4);
    }

    /**
     * Sets <code>value</code> as attribute value for D_4 using the alias name D4.
     * @param value value to set the D_4
     */
    public void setD4(String value) {
        setAttributeInternal(D4, value);
    }

    /**
     * Gets the attribute value for D_5 using the alias name D5.
     * @return the D_5
     */
    public String getD5() {
        return (String) getAttributeInternal(D5);
    }

    /**
     * Sets <code>value</code> as attribute value for D_5 using the alias name D5.
     * @param value value to set the D_5
     */
    public void setD5(String value) {
        setAttributeInternal(D5, value);
    }

    /**
     * Gets the attribute value for D_6 using the alias name D6.
     * @return the D_6
     */
    public String getD6() {
        return (String) getAttributeInternal(D6);
    }

    /**
     * Sets <code>value</code> as attribute value for D_6 using the alias name D6.
     * @param value value to set the D_6
     */
    public void setD6(String value) {
        setAttributeInternal(D6, value);
    }

    /**
     * Gets the attribute value for D_7 using the alias name D7.
     * @return the D_7
     */
    public String getD7() {
        return (String) getAttributeInternal(D7);
    }

    /**
     * Sets <code>value</code> as attribute value for D_7 using the alias name D7.
     * @param value value to set the D_7
     */
    public void setD7(String value) {
        setAttributeInternal(D7, value);
    }

    /**
     * Gets the attribute value for D_8 using the alias name D8.
     * @return the D_8
     */
    public String getD8() {
        return (String) getAttributeInternal(D8);
    }

    /**
     * Sets <code>value</code> as attribute value for D_8 using the alias name D8.
     * @param value value to set the D_8
     */
    public void setD8(String value) {
        setAttributeInternal(D8, value);
    }

    /**
     * Gets the attribute value for D_9 using the alias name D9.
     * @return the D_9
     */
    public String getD9() {
        return (String) getAttributeInternal(D9);
    }

    /**
     * Sets <code>value</code> as attribute value for D_9 using the alias name D9.
     * @param value value to set the D_9
     */
    public void setD9(String value) {
        setAttributeInternal(D9, value);
    }

    /**
     * Gets the attribute value for D_10 using the alias name D10.
     * @return the D_10
     */
    public String getD10() {
        return (String) getAttributeInternal(D10);
    }

    /**
     * Sets <code>value</code> as attribute value for D_10 using the alias name D10.
     * @param value value to set the D_10
     */
    public void setD10(String value) {
        setAttributeInternal(D10, value);
    }

    /**
     * Gets the attribute value for D_11 using the alias name D11.
     * @return the D_11
     */
    public String getD11() {
        return (String) getAttributeInternal(D11);
    }

    /**
     * Sets <code>value</code> as attribute value for D_11 using the alias name D11.
     * @param value value to set the D_11
     */
    public void setD11(String value) {
        setAttributeInternal(D11, value);
    }

    /**
     * Gets the attribute value for D_12 using the alias name D12.
     * @return the D_12
     */
    public String getD12() {
        return (String) getAttributeInternal(D12);
    }

    /**
     * Sets <code>value</code> as attribute value for D_12 using the alias name D12.
     * @param value value to set the D_12
     */
    public void setD12(String value) {
        setAttributeInternal(D12, value);
    }

    /**
     * Gets the attribute value for D_13 using the alias name D13.
     * @return the D_13
     */
    public String getD13() {
        return (String) getAttributeInternal(D13);
    }

    /**
     * Sets <code>value</code> as attribute value for D_13 using the alias name D13.
     * @param value value to set the D_13
     */
    public void setD13(String value) {
        setAttributeInternal(D13, value);
    }

    /**
     * Gets the attribute value for D_14 using the alias name D14.
     * @return the D_14
     */
    public String getD14() {
        return (String) getAttributeInternal(D14);
    }

    /**
     * Sets <code>value</code> as attribute value for D_14 using the alias name D14.
     * @param value value to set the D_14
     */
    public void setD14(String value) {
        setAttributeInternal(D14, value);
    }

    /**
     * Gets the attribute value for D_15 using the alias name D15.
     * @return the D_15
     */
    public String getD15() {
        return (String) getAttributeInternal(D15);
    }

    /**
     * Sets <code>value</code> as attribute value for D_15 using the alias name D15.
     * @param value value to set the D_15
     */
    public void setD15(String value) {
        setAttributeInternal(D15, value);
    }

    /**
     * Gets the attribute value for D_16 using the alias name D16.
     * @return the D_16
     */
    public String getD16() {
        return (String) getAttributeInternal(D16);
    }

    /**
     * Sets <code>value</code> as attribute value for D_16 using the alias name D16.
     * @param value value to set the D_16
     */
    public void setD16(String value) {
        setAttributeInternal(D16, value);
    }

    /**
     * Gets the attribute value for D_17 using the alias name D17.
     * @return the D_17
     */
    public String getD17() {
        return (String) getAttributeInternal(D17);
    }

    /**
     * Sets <code>value</code> as attribute value for D_17 using the alias name D17.
     * @param value value to set the D_17
     */
    public void setD17(String value) {
        setAttributeInternal(D17, value);
    }

    /**
     * Gets the attribute value for D_18 using the alias name D18.
     * @return the D_18
     */
    public String getD18() {
        return (String) getAttributeInternal(D18);
    }

    /**
     * Sets <code>value</code> as attribute value for D_18 using the alias name D18.
     * @param value value to set the D_18
     */
    public void setD18(String value) {
        setAttributeInternal(D18, value);
    }

    /**
     * Gets the attribute value for D_19 using the alias name D19.
     * @return the D_19
     */
    public String getD19() {
        return (String) getAttributeInternal(D19);
    }

    /**
     * Sets <code>value</code> as attribute value for D_19 using the alias name D19.
     * @param value value to set the D_19
     */
    public void setD19(String value) {
        setAttributeInternal(D19, value);
    }

    /**
     * Gets the attribute value for D_20 using the alias name D20.
     * @return the D_20
     */
    public String getD20() {
        return (String) getAttributeInternal(D20);
    }

    /**
     * Sets <code>value</code> as attribute value for D_20 using the alias name D20.
     * @param value value to set the D_20
     */
    public void setD20(String value) {
        setAttributeInternal(D20, value);
    }

    /**
     * Gets the attribute value for D_21 using the alias name D21.
     * @return the D_21
     */
    public String getD21() {
        return (String) getAttributeInternal(D21);
    }

    /**
     * Sets <code>value</code> as attribute value for D_21 using the alias name D21.
     * @param value value to set the D_21
     */
    public void setD21(String value) {
        setAttributeInternal(D21, value);
    }

    /**
     * Gets the attribute value for D_22 using the alias name D22.
     * @return the D_22
     */
    public String getD22() {
        return (String) getAttributeInternal(D22);
    }

    /**
     * Sets <code>value</code> as attribute value for D_22 using the alias name D22.
     * @param value value to set the D_22
     */
    public void setD22(String value) {
        setAttributeInternal(D22, value);
    }

    /**
     * Gets the attribute value for D_23 using the alias name D23.
     * @return the D_23
     */
    public String getD23() {
        return (String) getAttributeInternal(D23);
    }

    /**
     * Sets <code>value</code> as attribute value for D_23 using the alias name D23.
     * @param value value to set the D_23
     */
    public void setD23(String value) {
        setAttributeInternal(D23, value);
    }

    /**
     * Gets the attribute value for D_24 using the alias name D24.
     * @return the D_24
     */
    public String getD24() {
        return (String) getAttributeInternal(D24);
    }

    /**
     * Sets <code>value</code> as attribute value for D_24 using the alias name D24.
     * @param value value to set the D_24
     */
    public void setD24(String value) {
        setAttributeInternal(D24, value);
    }

    /**
     * Gets the attribute value for D_25 using the alias name D25.
     * @return the D_25
     */
    public String getD25() {
        return (String) getAttributeInternal(D25);
    }

    /**
     * Sets <code>value</code> as attribute value for D_25 using the alias name D25.
     * @param value value to set the D_25
     */
    public void setD25(String value) {
        setAttributeInternal(D25, value);
    }

    /**
     * Gets the attribute value for D_26 using the alias name D26.
     * @return the D_26
     */
    public String getD26() {
        return (String) getAttributeInternal(D26);
    }

    /**
     * Sets <code>value</code> as attribute value for D_26 using the alias name D26.
     * @param value value to set the D_26
     */
    public void setD26(String value) {
        setAttributeInternal(D26, value);
    }

    /**
     * Gets the attribute value for D_27 using the alias name D27.
     * @return the D_27
     */
    public String getD27() {
        return (String) getAttributeInternal(D27);
    }

    /**
     * Sets <code>value</code> as attribute value for D_27 using the alias name D27.
     * @param value value to set the D_27
     */
    public void setD27(String value) {
        setAttributeInternal(D27, value);
    }

    /**
     * Gets the attribute value for D_28 using the alias name D28.
     * @return the D_28
     */
    public String getD28() {
        return (String) getAttributeInternal(D28);
    }

    /**
     * Sets <code>value</code> as attribute value for D_28 using the alias name D28.
     * @param value value to set the D_28
     */
    public void setD28(String value) {
        setAttributeInternal(D28, value);
    }

    /**
     * Gets the attribute value for D_29 using the alias name D29.
     * @return the D_29
     */
    public String getD29() {
        return (String) getAttributeInternal(D29);
    }

    /**
     * Sets <code>value</code> as attribute value for D_29 using the alias name D29.
     * @param value value to set the D_29
     */
    public void setD29(String value) {
        setAttributeInternal(D29, value);
    }

    /**
     * Gets the attribute value for D_30 using the alias name D30.
     * @return the D_30
     */
    public String getD30() {
        return (String) getAttributeInternal(D30);
    }

    /**
     * Sets <code>value</code> as attribute value for D_30 using the alias name D30.
     * @param value value to set the D_30
     */
    public void setD30(String value) {
        setAttributeInternal(D30, value);
    }

    /**
     * Gets the attribute value for D_31 using the alias name D31.
     * @return the D_31
     */
    public String getD31() {
        return (String) getAttributeInternal(D31);
    }

    /**
     * Sets <code>value</code> as attribute value for D_31 using the alias name D31.
     * @param value value to set the D_31
     */
    public void setD31(String value) {
        setAttributeInternal(D31, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Total.
     * @return the Total
     */
    public Long getTotal() {
        Long tot = new Long(0);
        if("Y".equalsIgnoreCase(getD1())) {
            tot = tot+1;
        }
        if("Y".equalsIgnoreCase(getD2())) {
            tot = tot+1;
        }
        if("Y".equalsIgnoreCase(getD3())) {
            tot = tot+1;
        }
        if("Y".equalsIgnoreCase(getD4())) {
            tot = tot+1;
        }
        if("Y".equalsIgnoreCase(getD5())) {
            tot = tot+1;
        }
        if("Y".equalsIgnoreCase(getD6())) {
            tot = tot+1;
        }
        if("Y".equalsIgnoreCase(getD7())) {
            tot = tot+1;
        }
        if("Y".equalsIgnoreCase(getD8())) {
            tot = tot+1;
        }
        if("Y".equalsIgnoreCase(getD9())) {
            tot = tot+1;
        }
        if("Y".equalsIgnoreCase(getD10())) {
            tot = tot+1;
        }
        if("Y".equalsIgnoreCase(getD11())) {
            tot = tot+1;
        }
        if("Y".equalsIgnoreCase(getD12())) {
            tot = tot+1;
        }
        if("Y".equalsIgnoreCase(getD13())) {
            tot = tot+1;
        }
        if("Y".equalsIgnoreCase(getD14())) {
            tot = tot+1;
        }
        if("Y".equalsIgnoreCase(getD15())) {
            tot = tot+1;
        }
        if("Y".equalsIgnoreCase(getD16())) {
            tot = tot+1;
        }
        if("Y".equalsIgnoreCase(getD17())) {
            tot = tot+1;
        }
        if("Y".equalsIgnoreCase(getD18())) {
            tot = tot+1;
        }
        if("Y".equalsIgnoreCase(getD19())) {
            tot = tot+1;
        }
        if("Y".equalsIgnoreCase(getD20())) {
            tot = tot+1;
        }
        if("Y".equalsIgnoreCase(getD21())) {
            tot = tot+1;
        }
        if("Y".equalsIgnoreCase(getD22())) {
            tot = tot+1;
        }
        if("Y".equalsIgnoreCase(getD23())) {
            tot = tot+1;
        }
        if("Y".equalsIgnoreCase(getD24())) {
            tot = tot+1;
        }
        if("Y".equalsIgnoreCase(getD25())) {
            tot = tot+1;
        }
        if("Y".equalsIgnoreCase(getD26())) {
            tot = tot+1;
        }
        if("Y".equalsIgnoreCase(getD27())) {
            tot = tot+1;
        }
        if("Y".equalsIgnoreCase(getD28())) {
            tot = tot+1;
        }
        if("Y".equalsIgnoreCase(getD29())) {
            tot = tot+1;
        }
        if("Y".equalsIgnoreCase(getD30())) {
            tot = tot+1;
        }
        if("Y".equalsIgnoreCase(getD31())) {
            tot = tot+1;
        }
        return tot;
    }

    /**
     * Gets the view accessor <code>RowSet</code> SCommonLookupVA.
     */
    public RowSet getSCommonLookupVA() {
        return (RowSet) getAttributeInternal(SCOMMONLOOKUPVA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SSectionVA.
     */
    public RowSet getSSectionVA() {
        return (RowSet) getAttributeInternal(SSECTIONVA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SSessionVA.
     */
    public RowSet getSSessionVA() {
        return (RowSet) getAttributeInternal(SSESSIONVA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SClassVA.
     */
    public RowSet getSClassVA() {
        return (RowSet) getAttributeInternal(SCLASSVA);
    }
}

