package com.lab.kot.school.model.vo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Oct 15 01:21:59 IST 2016
// ---------------------------------------------------------------------
public interface SBookAllocationVO extends ViewObject {
    void createInit(Long bookId);
}

