package com.lab.kot.school.model.vo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Oct 02 17:54:30 IST 2016
// ---------------------------------------------------------------------
public interface SStudentVO extends ViewObject {
    void createNInit();
}

