package com.lab.kot.school.model.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 12 19:37:43 IST 2016
// ---------------------------------------------------------------------
public interface SchoolSystemAM extends ApplicationModule {
    void copyStudentToAttendance();

    void copyTeacherToAttendance();
}

